### ISSUE TITLE
Ignores "new" type if it's from typed

### ISSUE THREAD

**Issue by AlexKnauth** [bennn/require-typed-check#1]
For example `typed.rkt` has

``` racket
#lang typed/racket
(provide f)
(: f : (-> Positive-Fixnum Nonnegative-Fixnum))
(define (f x) (- x 1))
```

And `main.rkt` has

``` racket
#lang typed/racket
(require require-typed-check)
(require/typed/check require-typed-check/test/basic/typed
  [f (-> String String)])
(f 5050)
```

This type-checks even though `main.rkt` looks like it shouldn't type-check. Should it check that the "new" type (here, `(-> String String)`) is a super-type of the real type somehow?

This could lead to strange behavior if people switch between `require/typed` and `require/typed/check`. Programs that type-checked with `require/typed` won't type-check with `/check`, and programs that type-checked with `/check` won't type-check with normal `require/typed`.

**Comment by bennn** [comment]
Good catch. This has always been a problem with the gradual typing project & I've just used `require/typed` for debugging.

I think we can do better if we convert the annotations above to an `(void (ann f (-> String String)))`. (Sadly this means we'll have to copy/paste the parsing code from [prims-contract.rkt](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/base-env/prims-contract.rkt#L115) or [no-check-helper.rkt](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed/private/no-check-helper.rkt#L17) instead of just re-using the `require/typed` from `typed/racket/no-check`. But ok.)

BTW I had thought about submitting this library as a pull request to Typed Racket, but decided against it because:
- I couldn't figure out a sure way of checking whether any module/submodule was typed
- I don't like the use of `dynamic-require` and only see `compiled-module-submodules` as an alternative
- I don't think there's a strong practical use-case for this
  So in spirit I have given up on making `require/typed/check` perfect.
